[package]
org = "ballerinax"
name = "twitter"
version = "0.0.4"
license = ["Apache-2.0"]
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-twitter"
keywords = ["ballerina", "Twitter", "endpoint", "connector"]
